FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

ENV PATH="${PATH}:/root/.dotnet/tools"

COPY doqr-back/doqr.sln ./

COPY doqr-back/API/API.csproj ./API/
COPY doqr-back/Domain/Domain.csproj ./Domain/
COPY doqr-back/Infrastructure/Infrastructure.csproj ./Infrastructure/
COPY doqr-back/Application/Application.csproj ./Application/

RUN dotnet restore doqr.sln

COPY doqr-back/ ./

RUN dotnet publish API/API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "API.dll"]
